apiVersion: v1
kind: Pod
metadata:
  name: dev-test
  labels:
    name: dev-test
spec:
  containers:
  - name: dev-test
    image: node:8.11.4
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000
