apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-basics
spec:
  selector:
    matchLabels:
      app: http-basics
  template:
    metadata:
      labels:
        app: http-basics
    spec:
      containers:
      - name: http-basics
        image: neitofr/http_basics:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http-basics
          containerPort: 5050
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: http-basics-service
spec:
  type: LoadBalancer
  selector:
    app: http-basics
  ports:
  - port: 5050  
    targetPort: http-basics

