apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tea-ui
  template:
    metadata:
      labels:
        app: tea-ui
    spec:
      containers:
      - name: tea-ui
        env:
          - name: PROD_SERVER_PORT
            value: "80"
        image: neitofr/tea_ui:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: tea-ui
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tea-ui
spec:
  type: LoadBalancer
  selector:
    app: tea-ui
  ports:
  - port: 80
    targetPort: tea-ui
    protocol: TCP
