apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tea-api
  template:
    metadata:
      labels:
        app: tea-api
    spec:
      containers:
      - name: tea-api
        image: neitofr/tea_api:auto
        imagePullPolicy: Always
        env:
          - name: APP_PORT
            value: "3030"
          - name: MONGO_URL
            value: "mongodb://mongo:27017"
          - name: MONGO_DB
            value: "teas"
          - name: MONGO_COL
            value: "tea_list"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: tea-api
          containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: tea-api
spec:
  type: LoadBalancer
  selector:
    app: tea-api
  ports:
  - port: 3030
    targetPort: tea-api
    protocol: TCP